id: A088C862C
base_file: f9E41.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 21:47:10.362458
  last_modified_at: 2022-05-30 21:47:10.362465
